### ISSUE TITLE
filter partners according to their answers in surveys

### ISSUE THREAD

**Issue by MarkNorgate** [OCA/survey#13]
module: partner_survey
version: 8.0.1.0.0

**Steps to reproduce**
- ...email survey to existing partner.
  partner clicks on link in email and answers survey.
  go to partner list view.
  under advanced search, the following options exist:
  - Survey number
  - Surveys
  - Surveys answers

**Current behavior**
- Survey number appears to be populated with the number of surveys a partner has been sent? This has some use as a filter.
- Surveys and Surveys answers appear to be expecting a date to be entered as the filter value or the following occurs:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\http.py", line 536, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\http.py", line 573, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\http.py", line 309, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\http.py", line 306, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\http.py", line 802, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\http.py", line 402, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server\openerp\addons\web\controllers\main.py", line 877, in search_read
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server\openerp\addons\web\controllers\main.py", line 898, in do_search_read
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\http.py", line 907, in proxy
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\models.py", line 5129, in search_read
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\models.py", line 1642, in search
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server\openerp\addons\base\res\res_partner.py", line 656, in _search
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\models.py", line 4638, in _search
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\models.py", line 4461, in _where_calc
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\osv\expression.py", line 646, in __init__
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\osv\expression.py", line 930, in parse
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 336, in old_api
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\models.py", line 1723, in name_search
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 462, in new_api
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\models.py", line 1735, in _name_search
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\models.py", line 4656, in _search
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\sql_db.py", line 158, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150522\server.\openerp\sql_db.py", line 234, in execute
DataError: date/time field value out of range: "15"
LINE 1: ...input" WHERE ("survey_user_input"."date_create" = '15') ORDE...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.

**Expected behavior**
I expected to be able to 'filter partners according to their answers in surveys'?

**Comment by rafaelbn** [comment]
Please test it here: http://3136086-8-0-c06029.runbot2.odoo-community.org  and paste the traceback from runbot. Thanks

Ref: https://github.com/OCA/survey/pull/8

**Comment by MarkNorgate** [comment]
What username and password please?

**Comment by rafaelbn** [comment]
admin / admin

> Surveys and Surveys answers appear to be expecting a date to be entered as the filter value or the following occurs:

Check:

![26-11-2015 20-53-51](https://cloud.githubusercontent.com/assets/8736623/11429986/0321f97c-9480-11e5-82a2-2e0da9cbe6b2.png)

![26-11-2015 20-53-15](https://cloud.githubusercontent.com/assets/8736623/11429988/063dae30-9480-11e5-8355-175bccb5108f.png)

**Comment by rafaelbn** [comment]
@MarkNorgate please read this: https://odoo-community.org/page/review

I you can review also:
- https://github.com/OCA/survey/pull/6
- https://github.com/OCA/survey/pull/11
- https://github.com/OCA/survey/pull/4

**Comment by MarkNorgate** [comment]
I'm sorry, I don't understand what those screen shots have got to do with 'filter partners according to their answers in surveys'?
